name: lint
on:
  push:
  pull_request:
    types: [opened reopened syncronize closed]

jobs:
  test:
    name: Check mix format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24.x
          elixir-version: 1.12.0
      - name: Fetch dependencies
        run: mix deps.get
      - name: Check format
        run: mix format --check-formatted
      - name: Check code style
        run: mix credo
