name: lint
on:
  push:
  pull_request:
    types: [opened reopened syncronize closed]

jobs:
  test:
    name: Check mix format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Setup Elixir
        uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 21.x
          elixir-version: 1.9.1
      - name: Fetch dependencies
        run: mix deps.get
      - name: Check format
        run: mix format --check-formatted
      - name: Check code style
        run: mix credo
